### ISSUE TITLE
Consider to restrict DBAPI only for Presto engine

### ISSUE THREAD

**Issue by chezou** [treasure-data/pytd#33]
As @takuti mentioned at https://github.com/treasure-data/pytd/pull/30#issuecomment-514980178, `connect(pytd.Client(database='sample_datasets', default_engine='hive'))` might introduces some possibility of failure to use `cursor`. On this issue, we need to clarify what kind of issue will occur and should decide whether we have to limit using of Hive engine for DBAPI.

**Comment by takuti** [comment]
A bit more clarification - in fact, it's not "failure," but may introduce confusion for users.

Importantly, as [our README states](https://github.com/treasure-data/pytd#db-api
), we assume `cursor.fetchone()` fetches table records one-by-one; this is a more efficient option to retrieve large volume of data. However, when we call `cursor` with Hive, it internally uses [td-client-python](https://github.com/treasure-data/td-client-python)'s "synthetic" cursor implementation, which [actually fetches all records at once from job result](https://github.com/treasure-data/td-client-python/blob/6cf6dfbb60119f400274491d3e942d4f9fbcebd6/tdclient/cursor.py#L84-L94).

Thus, I originally thought it might be better to restrict DBAPI only for Presto so that it always behaves as we expect from the DBAPI spec.

**Comment by takuti** [comment]
But now, I changed my mind because active Hive users may be confused if we stop providing DBAPI for Hive. Therefore, in order to keep the compatibility, adding a warning message for the point that I mentioned above should be sufficient for now: https://github.com/treasure-data/pytd/blob/b1176b37e7841c0278d3c7c14525c91ed18e62c4/pytd/query_engine.py#L197-L204
